//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class officerreport
    {
        public int CUNSUMER_NO { get; set; }
        public string RANK { get; set; }
        public string NAME { get; set; }
        public string UNIT { get; set; }
        public string ADDRESS { get; set; }
        public string PIN_CODE { get; set; }
        public string SERVICE_NUMBER { get; set; }
        public string METER_NO { get; set; }
    }
}
