//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_billelectric
    {
        public int billelectric_id { get; set; }
        public System.DateTime billelectric_datetime { get; set; }
        public double billelectric_amount { get; set; }
        public int fk_paymentstatus { get; set; }
        public int fk_location { get; set; }
        public int fk_resident { get; set; }
        public double billelectric_prevreading { get; set; }
        public double billelectric_currentreading { get; set; }
        public double billelectric_units { get; set; }
        public double billelectric_water { get; set; }
        public double billelectric_tv { get; set; }
        public string billelectric_remarks { get; set; }
        public Nullable<int> fk_billpicture { get; set; }
        public string billelectric_month { get; set; }
        public Nullable<double> billelectric_outstanding { get; set; }
        public double billelectric_fpa { get; set; }
        public double billelectric_rebate { get; set; }
        public double billelectric_paymentamount { get; set; }
        public Nullable<System.DateTime> billelectric_paymentdate { get; set; }
        public string billelectric_paymentmonth { get; set; }
    }
}
