//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbl_users
{
    public int users_id { get; set; }
    public string users_username { get; set; }
    public string users_fullname { get; set; }
    public string users_password { get; set; }
    public int fk_usertype { get; set; }
    public int users_isActive { get; set; }
}
