//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ror
    {
        public int id { get; set; }
        public double ror_amount { get; set; }
        public System.DateTime ror_datetime { get; set; }
        public double ror_outstanding { get; set; }
        public int fk_resident { get; set; }
        public string consummer_no { get; set; }
        public string ror_month { get; set; }
        public int ror_status { get; set; }
    }
}
