//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbl_readingelectriclog
{
    public int readingelectriclog_id { get; set; }
    public System.DateTime readingelectriclog_datetime { get; set; }
    public string readingelectriclog_remarks { get; set; }
    public string readingelectriclog_meterno { get; set; }
    public double readingelectriclog_prevreading { get; set; }
    public double readingelectriclog_currentreading { get; set; }
    public double readingelectriclog_units { get; set; }
    public int readingelectriclog_addedby { get; set; }
    public string readingelectriclog_month { get; set; }
    public System.DateTime readingelectriclog_archivedon { get; set; }
    public int readingelectriclog_archivedby { get; set; }
}
