//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_readinggaslog
    {
        public int readinglog_id { get; set; }
        public System.DateTime readinglog_datetime { get; set; }
        public string readinglog_remarks { get; set; }
        public string readinglog_meterno { get; set; }
        public double readinglog_prevreading { get; set; }
        public double readinglog_currentreading { get; set; }
        public double readinglog_units { get; set; }
        public int readinglog_addedby { get; set; }
        public string readinglog_month { get; set; }
        public System.DateTime readinglog_archivedon { get; set; }
        public int readinglog_archivedby { get; set; }
    }
}
