//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userpermissions
    {
        public int userpermissions_id { get; set; }
        public Nullable<int> fk_action { get; set; }
        public Nullable<int> fk_user { get; set; }
        public string userpermissions_action { get; set; }
        public string userpermissions_controller { get; set; }
    }
}
