//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_residenthistory
    {
        public int residenthistory_id { get; set; }
        public int fk_resident { get; set; }
        public int fk_location { get; set; }
        public System.DateTime residenthistory_dateofoccupation { get; set; }
        public System.DateTime residenthistory_dateofvocation { get; set; }
        public string meter_no { get; set; }
    }
}
