//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbl_readingelectric
{
    public int readingelectric_id { get; set; }
    public System.DateTime readingelectric_datetime { get; set; }
    public string readingelectric_remarks { get; set; }
    public string readingelectric_meterno { get; set; }
    public double readingelectric_prevreading { get; set; }
    public double readingelectric_currentreading { get; set; }
    public int fk_readingpicture { get; set; }
    public double readingelectric_units { get; set; }
    public int readingelectric_addedby { get; set; }
    public string readingelectric_month { get; set; }
}
