//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_outstanding
    {
        public int outstanding_id { get; set; }
        public double outstanding_amount { get; set; }
        public System.DateTime outstanding_date { get; set; }
        public int fk_consummer_no { get; set; }
        public string outstanding_month { get; set; }
        public int fk_resident { get; set; }
        public int fk_location { get; set; }
    }
}
