//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_billpicture
    {
        public int billpicture_id { get; set; }
        public string billpicture_date { get; set; }
        public string billpicture_type { get; set; }
        public double billpicture_size { get; set; }
    }
}
