//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fixedrates
    {
        public int fixedrates_id { get; set; }
        public string fixedrates_name { get; set; }
        public double fixedrates_amount { get; set; }
        public int fk_type { get; set; }
        public string fixedrates_unit { get; set; }
    }
}
