//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_readingpicture
    {
        public int readingpicture_id { get; set; }
        public string readingpicture_data { get; set; }
        public string readingpicture_type { get; set; }
        public int readingpicture_size { get; set; }
    }
}
